export const companies: Array<
  | { provider: "greenhouse"; name: string; boardToken: string }
  | { provider: "lever"; name: string; site: string }
  | { provider: "workday"; name: string; tenant: string; site?: string; siteCandidates?: string[]; region?: string }
  | { provider: "amazon"; name: string; keywords?: string[] }
  | { provider: "ashby"; name: string; slug: string }
  | { provider: "teamtailor"; name: string; slug: string }
  | { provider: "smartrecruiters"; name: string; companyId: string }
  | { provider: "icims"; name: string; slug: string }
> = [
  // Greenhouse - Major SaaS/Tech Companies
  { provider: "greenhouse", name: "Stripe", boardToken: "stripe" },
  { provider: "greenhouse", name: "Cloudflare", boardToken: "cloudflare" },
  { provider: "greenhouse", name: "Datadog", boardToken: "datadog" },
  { provider: "greenhouse", name: "Notion", boardToken: "notion" },
  { provider: "greenhouse", name: "Snowflake", boardToken: "snowflakecomputing" },
  { provider: "greenhouse", name: "Databricks", boardToken: "databricks" },
  { provider: "greenhouse", name: "Atlassian", boardToken: "atlassian" },
  { provider: "greenhouse", name: "Elastic", boardToken: "elastic" },
  { provider: "greenhouse", name: "MongoDB", boardToken: "mongodb" },
  { provider: "greenhouse", name: "Confluent", boardToken: "confluent" },
  { provider: "greenhouse", name: "HashiCorp", boardToken: "hashicorp" },
  { provider: "greenhouse", name: "GitLab", boardToken: "gitlab" },
  { provider: "greenhouse", name: "GitHub", boardToken: "github" },
  { provider: "greenhouse", name: "Figma", boardToken: "figma" },
  { provider: "greenhouse", name: "Miro", boardToken: "miro" },
  { provider: "greenhouse", name: "Asana", boardToken: "asana" },
  { provider: "greenhouse", name: "CrowdStrike", boardToken: "crowdstrike" },
  { provider: "greenhouse", name: "Snyk", boardToken: "snyk" },
  { provider: "greenhouse", name: "HubSpot", boardToken: "hubspot" },
  { provider: "greenhouse", name: "Twilio", boardToken: "twilio" },
  { provider: "greenhouse", name: "Airtable", boardToken: "airtable" },
  { provider: "greenhouse", name: "Palantir", boardToken: "palantir" },
  { provider: "greenhouse", name: "OpenAI", boardToken: "openai" },
  { provider: "greenhouse", name: "Docker", boardToken: "docker" },
  { provider: "greenhouse", name: "Box", boardToken: "box" },
  { provider: "greenhouse", name: "Coinbase", boardToken: "coinbase" },
  { provider: "greenhouse", name: "Dropbox", boardToken: "dropbox" },
  { provider: "greenhouse", name: "Zoom", boardToken: "zoom" },
  { provider: "greenhouse", name: "Slack", boardToken: "slack" },
  { provider: "greenhouse", name: "Square", boardToken: "square" },
  { provider: "greenhouse", name: "Shopify", boardToken: "shopify" },
  { provider: "greenhouse", name: "Okta", boardToken: "okta" },
  { provider: "greenhouse", name: "Auth0", boardToken: "auth0" },
  { provider: "greenhouse", name: "PagerDuty", boardToken: "pagerduty" },
  { provider: "greenhouse", name: "New Relic", boardToken: "newrelic" },
  { provider: "greenhouse", name: "Splunk", boardToken: "splunk" },
  { provider: "greenhouse", name: "Tableau", boardToken: "tableau" },
  { provider: "greenhouse", name: "Looker", boardToken: "looker" },
  { provider: "greenhouse", name: "Segment", boardToken: "segment" },
  { provider: "greenhouse", name: "Mixpanel", boardToken: "mixpanel" },
  { provider: "greenhouse", name: "LaunchDarkly", boardToken: "launchdarkly" },
  { provider: "greenhouse", name: "Amplitude", boardToken: "amplitude" },
  { provider: "greenhouse", name: "Postman", boardToken: "postman" },
  { provider: "greenhouse", name: "JetBrains", boardToken: "jetbrains" },
  { provider: "greenhouse", name: "Redis", boardToken: "redislabs" },
  { provider: "greenhouse", name: "Cockroach Labs", boardToken: "cockroachlabs" },
  { provider: "greenhouse", name: "DigitalOcean", boardToken: "digitalocean" },
  { provider: "greenhouse", name: "Linode", boardToken: "linode" },
  { provider: "greenhouse", name: "Fastly", boardToken: "fastly" },
  { provider: "greenhouse", name: "Cloudinary", boardToken: "cloudinary" },
  { provider: "greenhouse", name: "SendGrid", boardToken: "sendgrid" },
  { provider: "greenhouse", name: "Mailchimp", boardToken: "mailchimp" },
  { provider: "greenhouse", name: "Zendesk", boardToken: "zendesk" },
  { provider: "greenhouse", name: "Intercom", boardToken: "intercom" },
  { provider: "greenhouse", name: "Freshworks", boardToken: "freshworks" },
  { provider: "greenhouse", name: "ServiceNow", boardToken: "servicenow" },
  { provider: "greenhouse", name: "Workday", boardToken: "workday" },
  { provider: "greenhouse", name: "Salesforce", boardToken: "salesforce" },

  // Lever - High-growth startups and scale-ups
  { provider: "lever", name: "Ramp", site: "ramp" },
  { provider: "lever", name: "Canva", site: "canva" },
  { provider: "lever", name: "Anthropic", site: "anthropic" },
  { provider: "lever", name: "Rippling", site: "rippling" },
  { provider: "lever", name: "Brex", site: "brex" },
  { provider: "lever", name: "Vercel", site: "vercel" },
  { provider: "lever", name: "Mercury", site: "mercury" },
  { provider: "lever", name: "Loom", site: "loom" },
  { provider: "lever", name: "Scale AI", site: "scaleai" },
  { provider: "lever", name: "Zapier", site: "zapier" },
  { provider: "lever", name: "Webflow", site: "webflow" },
  { provider: "lever", name: "Notion", site: "notion" },
  { provider: "lever", name: "Figma", site: "figma" },
  { provider: "lever", name: "Discord", site: "discord" },
  { provider: "lever", name: "Plaid", site: "plaid" },
  { provider: "lever", name: "Stripe", site: "stripe" },
  { provider: "lever", name: "Instacart", site: "instacart" },
  { provider: "lever", name: "DoorDash", site: "doordash" },
  { provider: "lever", name: "Robinhood", site: "robinhood" },
  { provider: "lever", name: "Coinbase", site: "coinbase" },
  { provider: "lever", name: "OpenSea", site: "opensea" },
  { provider: "lever", name: "Uniswap", site: "uniswap" },
  { provider: "lever", name: "Airtable", site: "airtable" },
  { provider: "lever", name: "Retool", site: "retool" },
  { provider: "lever", name: "Supabase", site: "supabase" },
  { provider: "lever", name: "PlanetScale", site: "planetscale" },
  { provider: "lever", name: "Railway", site: "railway" },
  { provider: "lever", name: "Fly.io", site: "fly" },

  // Workday - Enterprise companies
  {
    provider: "workday",
    name: "PayPal",
    tenant: "paypal",
    siteCandidates: ["jobs", "paypaljobs", "paypal", "paypalcareers", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Okta",
    tenant: "okta",
    siteCandidates: ["careers", "okta", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "ServiceNow",
    tenant: "servicenow",
    siteCandidates: ["careers", "jobs", "external", "SN_External_Career_Site"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Adobe",
    tenant: "adobe",
    siteCandidates: ["external_experienced", "experienced", "careers", "jobs", "external"],
    region: "wd5",
  },
  {
    provider: "workday",
    name: "Cisco",
    tenant: "cisco",
    siteCandidates: ["jobs", "careers", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "VMware",
    tenant: "vmware",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Intuit",
    tenant: "intuit",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Autodesk",
    tenant: "autodesk",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Workday",
    tenant: "workday",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Palo Alto Networks",
    tenant: "paloaltonetworks",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Fortinet",
    tenant: "fortinet",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Check Point",
    tenant: "checkpoint",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  { provider: "workday", name: "F5", tenant: "f5", siteCandidates: ["careers", "jobs", "external"], region: "wd1" },
  {
    provider: "workday",
    name: "NetApp",
    tenant: "netapp",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Pure Storage",
    tenant: "purestorage",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },
  {
    provider: "workday",
    name: "Nutanix",
    tenant: "nutanix",
    siteCandidates: ["careers", "jobs", "external"],
    region: "wd1",
  },

  // Amazon/AWS - Multiple keyword searches
  {
    provider: "amazon",
    name: "AWS",
    keywords: [
      "enterprise account executive",
      "strategic account executive",
      "named account executive",
      "account executive",
      "enterprise account manager",
      "named account manager",
      "global account manager",
      "sales executive",
      "enterprise sales",
      "strategic sales",
    ],
  },

  // Ashby - Modern startups
  { provider: "ashby", name: "Linear", slug: "linear" },
  { provider: "ashby", name: "Retool", slug: "retool" },
  { provider: "ashby", name: "Replit", slug: "replit" },
  { provider: "ashby", name: "Vanta", slug: "vanta" },
  { provider: "ashby", name: "PostHog", slug: "posthog" },
  { provider: "ashby", name: "Cursor", slug: "cursor" },
  { provider: "ashby", name: "Perplexity", slug: "perplexity" },
  { provider: "ashby", name: "Midjourney", slug: "midjourney" },
  { provider: "ashby", name: "Runway", slug: "runway" },
  { provider: "ashby", name: "Stability AI", slug: "stability" },
  { provider: "ashby", name: "Hugging Face", slug: "huggingface" },
  { provider: "ashby", name: "Weights & Biases", slug: "wandb" },
  { provider: "ashby", name: "Replicate", slug: "replicate" },
  { provider: "ashby", name: "Modal", slug: "modal" },
  { provider: "ashby", name: "Together AI", slug: "together" },

  // SmartRecruiters - Global enterprises
  { provider: "smartrecruiters", name: "Spotify", companyId: "Spotify" },
  { provider: "smartrecruiters", name: "Unity", companyId: "Unity" },
  { provider: "smartrecruiters", name: "Visa", companyId: "Visa" },
  { provider: "smartrecruiters", name: "Mastercard", companyId: "Mastercard" },
  { provider: "smartrecruiters", name: "American Express", companyId: "AmericanExpress" },
  { provider: "smartrecruiters", name: "JPMorgan Chase", companyId: "JPMorganChase" },
  { provider: "smartrecruiters", name: "Goldman Sachs", companyId: "GoldmanSachs" },
  { provider: "smartrecruiters", name: "Morgan Stanley", companyId: "MorganStanley" },
  { provider: "smartrecruiters", name: "BlackRock", companyId: "BlackRock" },
  { provider: "smartrecruiters", name: "Fidelity", companyId: "Fidelity" },
  { provider: "smartrecruiters", name: "Charles Schwab", companyId: "CharlesSchwab" },
  { provider: "smartrecruiters", name: "Capital One", companyId: "CapitalOne" },
  { provider: "smartrecruiters", name: "Wells Fargo", companyId: "WellsFargo" },
  { provider: "smartrecruiters", name: "Bank of America", companyId: "BankofAmerica" },
  { provider: "smartrecruiters", name: "Citi", companyId: "Citi" },

  // iCIMS - Traditional enterprises
  { provider: "icims", name: "F5", slug: "careers-f5" },
  { provider: "icims", name: "NCR", slug: "careers-ncr" },
  { provider: "icims", name: "Dell", slug: "careers-dell" },
  { provider: "icims", name: "HPE", slug: "careers-hpe" },
  { provider: "icims", name: "IBM", slug: "careers-ibm" },
  { provider: "icims", name: "Oracle", slug: "careers-oracle" },
  { provider: "icims", name: "SAP", slug: "careers-sap" },
  { provider: "icims", name: "Accenture", slug: "careers-accenture" },
  { provider: "icims", name: "Deloitte", slug: "careers-deloitte" },
  { provider: "icims", name: "PwC", slug: "careers-pwc" },
  { provider: "icims", name: "EY", slug: "careers-ey" },
  { provider: "icims", name: "KPMG", slug: "careers-kpmg" },
  { provider: "icims", name: "McKinsey", slug: "careers-mckinsey" },
  { provider: "icims", name: "BCG", slug: "careers-bcg" },
  { provider: "icims", name: "Bain", slug: "careers-bain" },

  // Teamtailor - European companies (may be filtered by US-only setting)
  { provider: "teamtailor", name: "Northvolt", slug: "northvolt" },
  { provider: "teamtailor", name: "Tink", slug: "tink" },
  { provider: "teamtailor", name: "Klarna", slug: "klarna" },
  { provider: "teamtailor", name: "King", slug: "king" },
  { provider: "teamtailor", name: "Mojang", slug: "mojang" },
  { provider: "teamtailor", name: "Epidemic Sound", slug: "epidemicsound" },
  { provider: "teamtailor", name: "iZettle", slug: "izettle" },
  { provider: "teamtailor", name: "Truecaller", slug: "truecaller" },
]
